import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" test='arst'> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <someTextWithEntityRefs>&amp; &#x00B7;</someTextWithEntityRefs>
        <div className="w-1/5 mx-auto my-0" > {children} </div>
      </body>
    </html>
  );
}
